/**
 * Where the fitted calibration mapping lives on disk.
 *
 * The brain page is the audit surface — narrative, reliability tables, worst
 * calls, and the fit as a fenced JSON block, all in one document a human can
 * read. This file is the OPERATIONAL surface: the live cycle needs the mapping
 * on every run, and a brain CLI round-trip is a fresh process with a PGLite
 * cold start and an embedding call, easily 30-60s. Paying that to read two
 * numbers would be absurd.
 *
 * Both are written from the same `CalibrationFit`, so they cannot disagree. If
 * the file is missing or unreadable the caller falls back to identity, which
 * means "apply no correction" — the safe direction for a failure to fall.
 */

import { existsSync, readFileSync, writeFileSync, renameSync } from "node:fs";
import { join } from "node:path";
import {
  IDENTITY_FIT,
  parseFit,
  serializeFit,
  type CalibrationFit,
} from "../../src/prediction/calibration-fit.ts";

const REPO_ROOT = join(import.meta.dir, "..", "..");

/** Beside `.prediction-state.json`, for the same reason: it is run state, not
 *  source, and it is regenerated by the nightly cycle. */
export const CALIBRATION_PATH = join(REPO_ROOT, ".prediction-calibration.json");

/**
 * Load the active mapping, or identity when there is none.
 *
 * Never throws. A corrupt file must not be able to stop a prediction run, and
 * it must certainly not be able to move a probability — both failure paths lead
 * to identity.
 */
export function loadCalibrationFit(path = CALIBRATION_PATH): CalibrationFit {
  if (!existsSync(path)) return IDENTITY_FIT;
  try {
    const raw = readFileSync(path, "utf-8");
    // Stored as the same fenced-JSON shape the brain page carries, so one
    // parser covers both and neither format can drift from the other.
    const fit = parseFit(raw) ?? parseFit(`\`\`\`json\n${raw}\n\`\`\``);
    if (!fit) {
      console.error(`[calibration-store] ${path} held no valid fit — using identity`);
      return IDENTITY_FIT;
    }
    return fit;
  } catch (err) {
    console.error(
      `[calibration-store] could not read ${path}: ${(err as Error).message} — using identity`,
    );
    return IDENTITY_FIT;
  }
}

/** Write via temp-file + rename so a crash mid-write cannot leave a truncated
 *  file that the next run would read as "no calibration". */
export function saveCalibrationFit(fit: CalibrationFit, path = CALIBRATION_PATH): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, serializeFit(fit), "utf-8");
  renameSync(tmp, path);
}
